### ISSUE TITLE
Dataverse files no longer available: "Technical Problem"

### ISSUE THREAD

**Issue by cleong110** [imatge-upc/slt_how2sign_wicv2023#13]
## 🐛 Bug

From the main README.md I try clicking the links to "the dataverse". 
* https://dataverse.csuc.cat/dataset.xhtml?persistentId=doi%3A10.34810%2Fdata693

and I just get this

![image](https://github.com/imatge-upc/slt_how2sign_wicv2023/assets/122366389/be27a009-ed4a-4204-8680-59ee2df05871)

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):
Open https://dataverse.csuc.cat/dataset.xhtml?persistentId=doi%3A10.34810%2Fdata693 in browser

### Expected behavior

Some sort of download or page load

### Environment

Firefox on Ubuntu 22.04, tried both Incognito mode and non incognito mode.

**Comment by LaiaTarres** [comment]
Sometimes the webpage has some issues. They messaged me that is working again. So I am closing this issue,
