### ISSUE TITLE
Has the I3D keypoints and .tsv dataset been uploaded yet?

### ISSUE THREAD

**Issue by tzjg7293** [imatge-upc/slt_how2sign_wicv2023#2]

**Comment by LaiaTarres** [comment]
Hi, the dataset needs a final approval from the university, but it will be available very soon.

**Comment by LaiaTarres** [comment]
Just in case, the data is already available in this [link](https://dataverse.csuc.cat/dataset.xhtml?persistentId=doi%3A10.34810%2Fdata693). Thanks all for using our repo!
