### ISSUE TITLE
Problem while training the corresponding sentencepiece model

### ISSUE THREAD

**Issue by rabeya-akter** [imatge-upc/slt_how2sign_wicv2023#4]
I am facing a problem while "Training the corresponding sentencepiece model".

As per instructions, I made the .env file like this:

FAIRSEQ_ROOT: /home/rmedu/Music/RabeyaAkter[SK-092-015]/thesis/Codes/slt_how2sign_wicv2023
SAVE_DIR: /home/rmedu/Music/RabeyaAkter[SK-092-015]/thesis/Dataset/tsvFile(cvpr23)
VOCAB_SIZE: 7000
FEATS: i3d
PARTITION: train

As per the dataset structure, in my SAVE_DIR path I have these files:

├── cvpr23.fairseq.i3d.train.how2sign.tsv
├── cvpr23.fairseq.i3d.val.how2sign.tsv
└── cvpr23.fairseq.i3d.test.how2sign.tsv

But I am getting this error everytime:

(slt-how2sign-wicv2023) rmedu@rmedu-desktop:~/Music/RabeyaAkter[SK-092-015]/thesis/Codes/slt_how2sign_wicv2023/examples/sign_language$ task how2sign:train_sentencepiece_lowercased
task: Specify the SAVE_DIR in the .env file.
task: precondition not met

**Can you tell me what am I doing wrong? What exactly should I change to solve this error?**

**Comment by FangSen9000** [comment]
Can you share your.env file, I'm having these damn problems too！

**Comment by ennauata** [comment]
@rabeya-akter, were you able to figure out this issue? Having the same problem here.

**Comment by rabeya-akter** [comment]
for this, you need a copy of the train csv file renamed as cvpr23.fairseq.mediapipe.train.how2sign.tsv and saved it in the slt_how2sign_wicv2023, that is in the root folder. This will work then.
