### ISSUE TITLE
Need help with extracting i3d feature

### ISSUE THREAD

**Issue by rabeya-akter** [imatge-upc/slt_how2sign_wicv2023#5]
Can you please guide us to the code to extract i3d feature?

**Comment by ruichengnew** [comment]
> Can you please guide us to the code to extract i3d feature?

Do you find the way to extract i3d feature from video?@rabeya-akter

**Comment by rabeya-akter** [comment]
No, the authors took the code from some other papers and they didn't make the code public yet.

**Comment by LaiaTarres** [comment]
Hi there, we directly use a pretrained feature extractor from [this project](https://imatge-upc.github.io/sl_retrieval/). However, they have not made the code or models publicly available. 
For now, you can use the features that we provide for the How2Sign.
